# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-flash_content-extension}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex K"]
  s.date = %q{2010-09-07}
  s.description = %q{Allows you to insert flash content}
  s.email = %q{flskif@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "app/models/flash_content_tags.rb",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "features/support/env.rb",
     "features/support/paths.rb",
     "flash_content_extension.rb",
     "lib/swfobject.rb",
     "lib/tasks/flash_content_extension_tasks.rake",
     "public/javascripts/radiant-flash_content-extension/swfobject.js",
     "public/swf/radiant-flash_content-extension/expressInstall.swf",
     "radiant-flash_content-extension.gemspec",
     "spec/models/flash_content_tags_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flskif/radiant-flash_content-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Flash Content Extension for Radiant CMS}
  s.test_files = [
    "spec/models/flash_content_tags_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.0"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.0"])
  end
end

